name: app-1
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  - name: build app-1
    uses: docker/build-push-action@v1.0.1
    with:
      repository: app-1
      tag_with_sha: true
      path: app-1
      push: false
    on:
      push:
        branches: [master]
